"""Phase N4 Step 6: reads all 15 outputs/<config>_seed<seed>/metrics.json
files and produces the gate check + main table + component-attribution
view + per-seed appendix, per the pre-registered Step 6 spec.

Usage:
    uv run python -m scripts.report_ablation_matrix
"""

from __future__ import annotations

import json
import statistics
from pathlib import Path

from rapport.data.constants import EMOTION_LABELS

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUTS_DIR = PROJECT_ROOT / "outputs"

CONFIGS = ["full", "minus_relational", "minus_shift", "minus_temporal", "base_fusion"]
SEEDS = (42, 1337, 2024)

# Pre-registered gates (docs/PHASE_N4.md Step 6 / phase instructions).
TEXT_ONLY_ANCHOR_MEAN = 0.6403
TEXT_ONLY_ANCHOR_STD = 0.0045
GATE_A_HARD_FLOOR = TEXT_ONLY_ANCHOR_MEAN - TEXT_ONLY_ANCHOR_STD  # 0.6358
GATE_B_TARGET = TEXT_ONLY_ANCHOR_MEAN  # 0.6403, "visible margin" above
TEXT_ONLY_FEAR_MEAN = 0.186
TEXT_ONLY_DISGUST_MEAN = 0.186


def load_metrics(config: str, seed: int) -> dict:
    path = OUTPUTS_DIR / f"{config}_seed{seed}" / "metrics.json"
    if not path.exists():
        raise FileNotFoundError(f"missing {path} -- run scripts/run_ablation_matrix.py first")
    return json.loads(path.read_text())


def mean_std(values: list[float]) -> tuple[float, float]:
    return statistics.mean(values), (statistics.stdev(values) if len(values) > 1 else 0.0)


def main() -> None:
    all_metrics = {config: {seed: load_metrics(config, seed) for seed in SEEDS} for config in CONFIGS}

    lines: list[str] = []
    lines.append("# PHASE N4 STEP 6 — gates + final reporting\n")
    lines.append(
        "Auto-generated by `scripts/report_ablation_matrix.py` from all 15 "
        "`outputs/<config>_seed<seed>/metrics.json` files. No significance "
        "tests at n=3, per instructions.\n"
    )

    # ---- Gate check (full config only) ----
    full_raw = [all_metrics["full"][s]["test_weighted_f1"] for s in SEEDS]
    full_macro = [all_metrics["full"][s]["test_macro_f1"] for s in SEEDS]
    full_nonzero = [all_metrics["full"][s]["all_7_classes_nonzero"] for s in SEEDS]
    full_fear = [all_metrics["full"][s]["test_per_class_f1"]["fear"] for s in SEEDS]
    full_disgust = [all_metrics["full"][s]["test_per_class_f1"]["disgust"] for s in SEEDS]

    raw_mean, raw_std = mean_std(full_raw)
    macro_mean, macro_std = mean_std(full_macro)
    fear_mean, _ = mean_std(full_fear)
    disgust_mean, _ = mean_std(full_disgust)

    gate_a_pass = raw_mean > GATE_A_HARD_FLOOR
    gate_b_pass = raw_mean > GATE_B_TARGET
    gate_c_pass = all(full_nonzero)

    lines.append("## Gate check (full config, 3-seed mean)\n")
    lines.append("| gate | criterion | required | actual | pass? |")
    lines.append("|---|---|---|---|---|")
    lines.append(
        f"| (a) HARD | mean raw weighted F1 > text anchor - 1 std | > {GATE_A_HARD_FLOOR:.4f} | "
        f"{raw_mean:.4f} | {'**PASS**' if gate_a_pass else '**FAIL**'} |"
    )
    lines.append(
        f"| (b) TARGET | mean raw weighted F1 > text anchor (visible margin) | > {GATE_B_TARGET:.4f} | "
        f"{raw_mean:.4f} | {'**PASS**' if gate_b_pass else '**MISS (not a stop gate)**'} |"
    )
    lines.append(
        f"| (c) | all 7 classes nonzero, every seed | 3/3 seeds | "
        f"{sum(full_nonzero)}/3 seeds | {'**PASS**' if gate_c_pass else '**FAIL**'} |"
    )
    lines.append("")
    lines.append(
        f"`full` mean macro F1: {macro_mean:.4f} ± {macro_std:.4f}. Fear/disgust means: "
        f"{fear_mean:.4f} / {disgust_mean:.4f} vs. the text-only anchor's "
        f"{TEXT_ONLY_FEAR_MEAN:.3f} / {TEXT_ONLY_DISGUST_MEAN:.3f} "
        f"(delta: {fear_mean - TEXT_ONLY_FEAR_MEAN:+.4f} / {disgust_mean - TEXT_ONLY_DISGUST_MEAN:+.4f}).\n"
    )

    # ---- Main table ----
    lines.append("## Main table (mean ± std across 3 seeds)\n")
    lines.append(
        "| config | raw weighted F1 | raw macro F1 | adj (tau=0.25) weighted F1 | adj macro F1 | "
        "neutral | joy | sadness | anger | surprise | fear | disgust | all-7-nonzero (seeds) |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")

    per_config_means: dict[str, dict] = {}
    for config in CONFIGS:
        raw_w = [all_metrics[config][s]["test_weighted_f1"] for s in SEEDS]
        raw_m = [all_metrics[config][s]["test_macro_f1"] for s in SEEDS]
        adj_w = [all_metrics[config][s]["test_posthoc_adjusted_result"]["weighted_f1"] for s in SEEDS]
        adj_m = [all_metrics[config][s]["test_posthoc_adjusted_result"]["macro_f1"] for s in SEEDS]
        nonzero = [all_metrics[config][s]["all_7_classes_nonzero"] for s in SEEDS]

        per_class_means = {}
        for cls in EMOTION_LABELS:
            vals = [all_metrics[config][s]["test_per_class_f1"][cls] for s in SEEDS]
            per_class_means[cls] = mean_std(vals)[0]

        raw_w_mean, raw_w_std = mean_std(raw_w)
        raw_m_mean, raw_m_std = mean_std(raw_m)
        adj_w_mean, adj_w_std = mean_std(adj_w)
        adj_m_mean, adj_m_std = mean_std(adj_m)

        per_config_means[config] = {
            "raw_weighted": raw_w_mean,
            "raw_macro": raw_m_mean,
            "adj_weighted": adj_w_mean,
            "adj_macro": adj_m_mean,
            "per_class": per_class_means,
        }

        per_class_str = " | ".join(f"{per_class_means[c]:.3f}" for c in EMOTION_LABELS)
        lines.append(
            f"| {config} | {raw_w_mean:.4f}±{raw_w_std:.4f} | {raw_m_mean:.4f}±{raw_m_std:.4f} | "
            f"{adj_w_mean:.4f}±{adj_w_std:.4f} | {adj_m_mean:.4f}±{adj_m_std:.4f} | {per_class_str} | "
            f"{sum(nonzero)}/3 |"
        )
    lines.append("")

    # ---- Component-attribution view ----
    lines.append("## Component attribution (deltas vs. base_fusion AND vs. text-only anchor)\n")
    lines.append("| config | delta raw weighted F1 vs base_fusion | delta raw weighted F1 vs text-only (0.6403) |")
    lines.append("|---|---|---|")
    base_fusion_raw = per_config_means["base_fusion"]["raw_weighted"]
    for config in CONFIGS:
        raw_w_mean = per_config_means[config]["raw_weighted"]
        lines.append(
            f"| {config} | {raw_w_mean - base_fusion_raw:+.4f} | {raw_w_mean - TEXT_ONLY_ANCHOR_MEAN:+.4f} |"
        )
    lines.append("")

    # ---- Per-seed appendix ----
    lines.append("## Per-seed appendix\n")
    lines.append("| config | seed | raw weighted F1 | raw macro F1 | adj weighted F1 | adj macro F1 | all-7-nonzero |")
    lines.append("|---|---|---|---|---|---|---|")
    for config in CONFIGS:
        for seed in SEEDS:
            m = all_metrics[config][seed]
            adj = m["test_posthoc_adjusted_result"]
            lines.append(
                f"| {config} | {seed} | {m['test_weighted_f1']:.4f} | {m['test_macro_f1']:.4f} | "
                f"{adj['weighted_f1']:.4f} | {adj['macro_f1']:.4f} | {m['all_7_classes_nonzero']} |"
            )
    lines.append("")

    report_text = "\n".join(lines)
    out_path = PROJECT_ROOT / "docs" / "PHASE_N4_STEP6.md"
    out_path.write_text(report_text)
    print(f"[done] wrote {out_path}")
    print(report_text)


if __name__ == "__main__":
    main()
