"""Phase N4-R Step 4: gate check + report for the compact 9-run residual
re-evaluation ({base_fusion_R, full_R, minus_relational_R} x 3 seeds).

Gates (pre-registered):
  (a) HARD, now structural: no config's mean raw weighted F1 below 0.6358
      (the same floor as Phase N4's original HARD gate).
  (b) DECISION: full_R vs base_fusion_R delta (weighted F1, macro F1) and
      fear/disgust per-class deltas -- decides whether relational memory
      + shift appear in the paper as contributions or as an analyzed
      negative result.

Usage:
    uv run python -m scripts.report_n4r_step4
"""

from __future__ import annotations

import json
import statistics
from pathlib import Path

from rapport.data.constants import EMOTION_LABELS

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUTS_DIR = PROJECT_ROOT / "outputs"

CONFIGS = ["base_fusion_R", "minus_relational_R", "full_R"]
SEEDS = (42, 1337, 2024)

HARD_FLOOR = 0.6358  # same structural floor as Phase N4's original HARD gate
TEXT_ONLY_ANCHOR_MEAN = 0.6403
TEXT_ONLY_FEAR_MEAN = 0.186
TEXT_ONLY_DISGUST_MEAN = 0.186


def load_metrics(config: str, seed: int) -> dict:
    path = OUTPUTS_DIR / f"{config}_seed{seed}" / "metrics.json"
    return json.loads(path.read_text())


def mean_std(values: list[float]) -> tuple[float, float]:
    return statistics.mean(values), (statistics.stdev(values) if len(values) > 1 else 0.0)


def main() -> None:
    all_metrics = {config: {seed: load_metrics(config, seed) for seed in SEEDS} for config in CONFIGS}

    lines: list[str] = []
    lines.append("# PHASE N4-R STEP 4 — compact re-run gates + report\n")
    lines.append(
        "Auto-generated by `scripts/report_n4r_step4.py` from all 9 "
        "`outputs/<config>_R_seed<seed>/metrics.json` files. No significance "
        "tests at n=3, per instructions.\n"
    )

    per_config_stats: dict[str, dict] = {}
    for config in CONFIGS:
        raw_w = [all_metrics[config][s]["test_weighted_f1"] for s in SEEDS]
        raw_m = [all_metrics[config][s]["test_macro_f1"] for s in SEEDS]
        per_class_means = {
            cls: mean_std([all_metrics[config][s]["test_per_class_f1"][cls] for s in SEEDS])[0]
            for cls in EMOTION_LABELS
        }
        nonzero = [all_metrics[config][s]["all_7_classes_nonzero"] for s in SEEDS]
        per_config_stats[config] = {
            "raw_weighted_mean": mean_std(raw_w)[0],
            "raw_weighted_std": mean_std(raw_w)[1],
            "raw_macro_mean": mean_std(raw_m)[0],
            "raw_macro_std": mean_std(raw_m)[1],
            "per_class": per_class_means,
            "all_7_nonzero_seeds": sum(nonzero),
            "raw_weighted_per_seed": raw_w,
        }

    # ---- Gate (a): HARD structural floor ----
    lines.append("## Gate (a) — HARD, structural: no config below 0.6358\n")
    lines.append("| config | mean raw weighted F1 | std | pass? |")
    lines.append("|---|---|---|---|")
    gate_a_all_pass = True
    for config in CONFIGS:
        s = per_config_stats[config]
        passed = s["raw_weighted_mean"] > HARD_FLOOR
        gate_a_all_pass = gate_a_all_pass and passed
        lines.append(
            f"| {config} | {s['raw_weighted_mean']:.4f} | {s['raw_weighted_std']:.4f} | "
            f"{'**PASS**' if passed else '**FAIL**'} |"
        )
    lines.append(f"\n**Gate (a) overall: {'PASS' if gate_a_all_pass else 'FAIL'}**\n")

    # ---- Gate (b): DECISION -- full_R vs base_fusion_R ----
    lines.append("## Gate (b) — DECISION: full_R vs base_fusion_R\n")
    full_r = per_config_stats["full_R"]
    base_r = per_config_stats["base_fusion_R"]
    minus_rel_r = per_config_stats["minus_relational_R"]

    delta_weighted = full_r["raw_weighted_mean"] - base_r["raw_weighted_mean"]
    delta_macro = full_r["raw_macro_mean"] - base_r["raw_macro_mean"]
    delta_fear = full_r["per_class"]["fear"] - base_r["per_class"]["fear"]
    delta_disgust = full_r["per_class"]["disgust"] - base_r["per_class"]["disgust"]

    lines.append(f"- delta raw weighted F1 (full_R - base_fusion_R): **{delta_weighted:+.4f}**")
    lines.append(f"- delta raw macro F1 (full_R - base_fusion_R): **{delta_macro:+.4f}**")
    lines.append(f"- delta fear F1 (full_R - base_fusion_R): **{delta_fear:+.4f}** (full_R={full_r['per_class']['fear']:.4f}, base_fusion_R={base_r['per_class']['fear']:.4f})")
    lines.append(f"- delta disgust F1 (full_R - base_fusion_R): **{delta_disgust:+.4f}** (full_R={full_r['per_class']['disgust']:.4f}, base_fusion_R={base_r['per_class']['disgust']:.4f})")
    lines.append(
        f"- for reference, delta vs. minus_relational_R (relational's own marginal contribution): "
        f"weighted F1 {full_r['raw_weighted_mean'] - minus_rel_r['raw_weighted_mean']:+.4f}, "
        f"fear F1 {full_r['per_class']['fear'] - minus_rel_r['per_class']['fear']:+.4f}, "
        f"disgust F1 {full_r['per_class']['disgust'] - minus_rel_r['per_class']['disgust']:+.4f}"
    )
    lines.append("")

    # ---- Main table ----
    lines.append("## Main table (mean ± std across 3 seeds)\n")
    lines.append(
        "| config | raw weighted F1 | raw macro F1 | neutral | joy | sadness | anger | surprise | fear | disgust | all-7-nonzero (seeds) |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for config in CONFIGS:
        s = per_config_stats[config]
        per_class_str = " | ".join(f"{s['per_class'][c]:.3f}" for c in EMOTION_LABELS)
        lines.append(
            f"| {config} | {s['raw_weighted_mean']:.4f}±{s['raw_weighted_std']:.4f} | "
            f"{s['raw_macro_mean']:.4f}±{s['raw_macro_std']:.4f} | {per_class_str} | {s['all_7_nonzero_seeds']}/3 |"
        )
    lines.append("")

    # ---- vs text-only anchor ----
    lines.append("## vs. Phase T text-only anchor (0.6403 mean raw weighted F1)\n")
    lines.append("| config | delta vs text-only anchor |")
    lines.append("|---|---|")
    for config in CONFIGS:
        s = per_config_stats[config]
        lines.append(f"| {config} | {s['raw_weighted_mean'] - TEXT_ONLY_ANCHOR_MEAN:+.4f} |")
    lines.append("")

    # ---- Per-seed appendix ----
    lines.append("## Per-seed appendix\n")
    lines.append("| config | seed | raw weighted F1 | raw macro F1 | all-7-nonzero |")
    lines.append("|---|---|---|---|---|")
    for config in CONFIGS:
        for seed in SEEDS:
            m = all_metrics[config][seed]
            lines.append(
                f"| {config} | {seed} | {m['test_weighted_f1']:.4f} | {m['test_macro_f1']:.4f} | "
                f"{m['all_7_classes_nonzero']} |"
            )
    lines.append("")

    report_text = "\n".join(lines)
    out_path = PROJECT_ROOT / "docs" / "PHASE_N4R_STEP4.md"
    out_path.write_text(report_text)
    print(f"[done] wrote {out_path}")
    print(report_text)


if __name__ == "__main__":
    main()
